algoritmo "temperatura"
// Função : falar se ta frio ou no
// Autor :  Bruno Sorrilha
// Data : 25/05/2023
// Seção de Declarações 
var
temp:real

inicio
// Seção de Comandos
escreval("qual a temperatura que deseja medir?")
leia(temp)

se (temp < 20) entao

escreval("que friaca *treme treme*")

se (temp <25) e (temp >20) entao

escreval("que temperatura boa piah")

se (temp > 25) entao

escreval("que calorão piah")

fimse
fimse
fimalgoritmo

