algoritmo "VisualG 3"
// Função : Dizer se alg é maior ou menor de idade
// Autor :
// Data : 18/05/2023
// Seção de Declarações 
var
idade: inteiro
nome: caractere

inicio
// Seção de Comandos 
escreval ("Qual seu nome?")
leia (nome)

escreval ("Qual sua idade?")
leia (idade)

se (idade >= 18) entao
escreval(nome," voce é maior de idade!")

senao
escreval(nome," voce é menor de idade")

fimse

fimalgoritmo
